CREATE TYPE "SourceKind" AS ENUM ('NAGER','OPEN_HOLIDAYS','DATA_GOUV_FR','TICKETMASTER','OPEN_METEO','MANUAL','COMP_SET','AMADEUS_STUB','GOOGLE_TRENDS_STUB');
CREATE TYPE "EventCategory" AS ENUM ('FESTIVAL','SPORT','CONGRESS','THEME_PARK','OTHER');
CREATE TYPE "ThemeParkStatus" AS ENUM ('OPEN','CLOSED','SPECIAL_EVENT','TO_CONFIRM');
CREATE TYPE "MealPlan" AS ENUM ('SA','AD','MP','TI');
CREATE TYPE "ImportOrigin" AS ENUM ('CSV','API');

CREATE TABLE "DataSourceState" ("id" TEXT PRIMARY KEY, "source" "SourceKind" NOT NULL UNIQUE, "lastSuccessAt" TIMESTAMP(3), "lastAttemptAt" TIMESTAMP(3), "status" TEXT NOT NULL DEFAULT 'pending', "records" INTEGER NOT NULL DEFAULT 0, "errorMessage" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PublicHoliday" ("id" TEXT PRIMARY KEY, "externalId" TEXT NOT NULL UNIQUE, "date" DATE NOT NULL, "countryCode" VARCHAR(2) NOT NULL, "subdivisionCode" VARCHAR(12), "localName" TEXT NOT NULL, "name" TEXT NOT NULL, "isNational" BOOLEAN NOT NULL DEFAULT true, "isBridge" BOOLEAN NOT NULL DEFAULT false, "sourceUrl" TEXT NOT NULL, "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "PublicHoliday_date_countryCode_idx" ON "PublicHoliday"("date", "countryCode");
CREATE TABLE "SchoolHoliday" ("id" TEXT PRIMARY KEY, "externalId" TEXT NOT NULL UNIQUE, "countryCode" VARCHAR(2) NOT NULL, "subdivisionCode" TEXT, "zone" TEXT, "name" TEXT NOT NULL, "startDate" DATE NOT NULL, "endDate" DATE NOT NULL, "source" "SourceKind" NOT NULL, "sourceUrl" TEXT, "confirmed" BOOLEAN NOT NULL DEFAULT true, "notes" TEXT, "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "SchoolHoliday_startDate_endDate_countryCode_idx" ON "SchoolHoliday"("startDate", "endDate", "countryCode");
CREATE TABLE "ExternalEvent" ("id" TEXT PRIMARY KEY, "externalId" TEXT NOT NULL UNIQUE, "name" TEXT NOT NULL, "startDate" TIMESTAMP(3) NOT NULL, "endDate" TIMESTAMP(3), "venue" TEXT, "city" TEXT, "latitude" DOUBLE PRECISION, "longitude" DOUBLE PRECISION, "venueCapacity" INTEGER, "impact" INTEGER NOT NULL DEFAULT 2, "sourceUrl" TEXT, "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "ExternalEvent_startDate_idx" ON "ExternalEvent"("startDate");
CREATE TABLE "WeatherForecast" ("id" TEXT PRIMARY KEY, "date" DATE NOT NULL UNIQUE, "temperatureMax" DOUBLE PRECISION NOT NULL, "precipitationChance" INTEGER NOT NULL, "weatherCode" INTEGER NOT NULL, "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "ManualEvent" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL, "startDate" DATE NOT NULL, "endDate" DATE NOT NULL, "category" "EventCategory" NOT NULL, "impact" INTEGER NOT NULL, "notes" TEXT, "source" TEXT, "confirmed" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "ManualEvent_startDate_endDate_idx" ON "ManualEvent"("startDate", "endDate");
CREATE TABLE "ThemeParkDay" ("id" TEXT PRIMARY KEY, "date" DATE NOT NULL UNIQUE, "status" "ThemeParkStatus" NOT NULL, "label" TEXT, "confirmed" BOOLEAN NOT NULL DEFAULT false, "source" TEXT, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CompetitorHotel" ("id" TEXT PRIMARY KEY, "name" TEXT NOT NULL UNIQUE, "active" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CompetitorRate" ("id" TEXT PRIMARY KEY, "competitorHotelId" TEXT NOT NULL REFERENCES "CompetitorHotel"("id") ON DELETE CASCADE, "stayDate" DATE NOT NULL, "queriedAt" TIMESTAMP(3) NOT NULL, "price" DECIMAL(10,2) NOT NULL, "mealPlan" "MealPlan" NOT NULL, "notes" TEXT, "source" TEXT NOT NULL DEFAULT 'manual', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "CompetitorRate_hotel_stay_query_meal_key" ON "CompetitorRate"("competitorHotelId", "stayDate", "queriedAt", "mealPlan");
CREATE INDEX "CompetitorRate_stayDate_queriedAt_idx" ON "CompetitorRate"("stayDate", "queriedAt");
CREATE TABLE "ScoreWeight" ("key" TEXT PRIMARY KEY, "label" TEXT NOT NULL, "value" INTEGER NOT NULL, "description" TEXT, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "SeasonalWeight" ("month" INTEGER PRIMARY KEY, "value" INTEGER NOT NULL, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "EmitterMarket" ("code" TEXT PRIMARY KEY, "label" TEXT NOT NULL, "active" BOOLEAN NOT NULL DEFAULT true, "weight" INTEGER NOT NULL DEFAULT 5, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "FutureMarketSignal" ("id" TEXT PRIMARY KEY, "provider" "SourceKind" NOT NULL, "date" DATE NOT NULL, "market" TEXT, "airportCode" TEXT, "value" DOUBLE PRECISION, "payload" JSONB, "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "FutureMarketSignal_provider_date_idx" ON "FutureMarketSignal"("provider", "date");
CREATE TABLE "PmsSnapshot" ("id" TEXT PRIMARY KEY, "snapshotDate" DATE NOT NULL, "stayDate" DATE NOT NULL, "roomsSold" INTEGER NOT NULL, "roomsAvailable" INTEGER NOT NULL, "adr" DECIMAL(10,2) NOT NULL, "revenue" DECIMAL(12,2) NOT NULL, "channel" TEXT NOT NULL DEFAULT '', "segment" TEXT NOT NULL DEFAULT '', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "PmsSnapshot_snapshot_stay_channel_segment_key" ON "PmsSnapshot"("snapshotDate", "stayDate", "channel", "segment");
CREATE INDEX "PmsSnapshot_stayDate_snapshotDate_idx" ON "PmsSnapshot"("stayDate", "snapshotDate");
CREATE TABLE "PmsImportLog" ("id" TEXT PRIMARY KEY, "importedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "origin" "ImportOrigin" NOT NULL, "rows" INTEGER NOT NULL, "user" TEXT, "errors" JSONB);
